using System.Collections.Generic;

#if UNITY_EDITOR || DEVELOPMENT_BUILD
public enum CombatFeelParameter
{
    MasterIntensity,
    DamageInfluence, MinFeedback, MaxFeedback, CritMultiplier,
    BasicWeight, EliteWeight, BossWeight, DirectionInfluence,
    DirectionRandomness, TangentialSpread,

    ShotInputDelay, FireResponseOffset, ShotAnimationLead, ShotFxLead,
    FireRateFeelMultiplier, CadenceVariance, BurstRhythmBias, FirstShotEmphasis,
    WeaponKickDistance, WeaponKickDuration, WeaponReturnDuration,
    WeaponOvershoot, WeaponSettleDuration, WeaponKickRotation,
    WeaponKickRandomness, WeaponScalePunchX, WeaponScalePunchY,
    PlayerVisualRecoil, PlayerVisualRecoilDuration, PlayerSquash,
    PlayerStretch, PlayerRotationKick, PlayerReturnSpring,
    PhysicalRecoil, PlayerRecoilVelocity, MovementDamp, MovementDampDuration,
    MuzzleScale, MuzzleDuration, MuzzleBrightness, MuzzleRandomRotation,
    MuzzleStretch, MuzzleSparks, MuzzleDirectionality,
    MuzzleRingScale, MuzzleRingDuration, MuzzleRingOpacity,

    ProjectileScale, ProjectileStretch, ProjectileSquash, ProjectileAlign,
    ProjectileSpin, ProjectileGlow, ProjectileBrightness, ProjectilePulse,
    ProjectilePulseSpeed, TrailWidth, TrailLength, TrailLifetime,
    TrailOpacity, TrailTaper, SpeedIllusion, ForwardVisualOffset,
    InitialStreakLength, InitialStreakLifetime,

    ImpactScale, ImpactLifetime, ImpactBrightness, ImpactRotationRandomness,
    ImpactDirectionality, ImpactRingSize, ImpactRingSpeed, ImpactRingLifetime,
    ImpactSparks, ImpactDebris, ForwardSpray, BackSpray, SideSpray,
    FlashStrength, FlashAttack, FlashHold, FlashRelease, BrightnessPunch,
    SaturationPunch, ContrastPunch,
    PopupInitialScale, PopupScalePunch, PopupRiseSpeed, PopupRiseDistance,
    PopupLifetime, PopupFadeDelay, PopupFadeDuration, PopupHorizontalDrift,
    PopupDriftRandomness, PopupRotation, PopupRotationRandomness,
    CritPopupScale, CritPopupRise, CritPopupPunch, CritPopupLifetime,
    PopupDelay,

    VisualHitPush, HitPushDuration, HitReturnDuration, HitOvershoot,
    HitSquashX, HitStretchY, HitSquashDuration, HitRestoreDuration,
    HitRotation, HitRotationRandomness, HitRotationReturn,
    WobbleStrength, WobbleFrequency, WobbleDamping, VisualStagger,
    PhysicalStagger,

    DeathPush, DeathRotation, DeathSquash, DeathStretch, DeathScalePunch,
    DeathHold, DeathFlash, DeathFlashDuration, DeathFade, DeathShrink,
    DeathExpand, DeathParticleAmount, DeathParticleScale, DeathParticleSpeed,
    DeathParticleLifetime, DeathDirectionality, DeathRingSize, DeathRingSpeed,
    DeathRingOpacity, GhostEnabled, GhostLifetime, GhostPush, GhostScale,
    GhostFade, OverkillThreshold, OverkillFeedback, OverkillParticles,
    OverkillDeathPush,

    ShotShakeAmplitude, ShotShakeFrequency, ShotShakeDuration,
    HitShakeAmplitude, HitShakeFrequency, HitShakeDuration,
    KillShakeAmplitude, KillShakeDuration, DirectionalKickDistance,
    DirectionalKickDuration, DirectionalReturn, DirectionalOvershoot,
    ShotZoomPunch, HitZoomPunch, KillZoomPunch, ZoomAttack, ZoomReturn,
    CameraSpring, CameraDamping, CameraOvershoot, TowardShot,
    AwayFromShot, TowardHit,

    ShotFreeze, ShotSlowdown, ShotSlowdownScale, ShotRecovery,
    HitFreeze, HitSlowdown, HitSlowdownScale, HitRecovery,
    KillFreeze, KillSlowdown, KillSlowdownScale, KillRecovery,
    EliteTimeEmphasis, BossTimeEmphasis, LocalEnemyFreeze, GlobalFreeze,
    FreezeBlend,

    CrowdRadius, CrowdStrength, CrowdFalloff, CrowdMaxTargets,
    CrowdFlash, CrowdWobble, KillShockwave,
    RapidKillWindow, RapidKillGain, RapidKillMax, RapidKillDecay,

    HitVignette, KillVignette, ScreenBrightness, ScreenSaturation,
    LocalHitLight, LocalHitRadius, LocalHitIntensity, LocalHitLifetime,
    PreFireDuration, PreFireGlow, PreFireCompression, PreFireAimEmphasis,

    MouseLookAhead, LookAheadDistance, LookAheadResponse, LookAheadReturn,
    LookAheadDeadZone, LookAheadCurve, HorizontalStrength, VerticalStrength,
    MaxScreenFraction
}

/// <summary>Read-only values consumed by combat presentation components.</summary>
public interface ICombatFeelSettings
{
    int Version { get; }
    float Get(CombatFeelParameter parameter);
}

/// <summary>Neutral runtime values shared with the development tuning descriptors.</summary>
public static class CombatFeelParameterDefaults
{
    private static readonly Dictionary<CombatFeelParameter, float> values = new()
    {
            [CombatFeelParameter.MasterIntensity] = 1,
            [CombatFeelParameter.DamageInfluence] = 0,
            [CombatFeelParameter.MinFeedback] = 0.7f,
            [CombatFeelParameter.MaxFeedback] = 1.4f,
            [CombatFeelParameter.CritMultiplier] = 1,
            [CombatFeelParameter.BasicWeight] = 1,
            [CombatFeelParameter.EliteWeight] = 1,
            [CombatFeelParameter.BossWeight] = 1,
            [CombatFeelParameter.DirectionInfluence] = 1,
            [CombatFeelParameter.DirectionRandomness] = 0,
            [CombatFeelParameter.FirstShotEmphasis] = 0,
            [CombatFeelParameter.WeaponKickDistance] = 0,
            [CombatFeelParameter.WeaponKickDuration] = .025f,
            [CombatFeelParameter.WeaponReturnDuration] = .08f,
            [CombatFeelParameter.WeaponOvershoot] = 0,
            [CombatFeelParameter.WeaponSettleDuration] = .06f,
            [CombatFeelParameter.WeaponKickRotation] = 0,
            [CombatFeelParameter.WeaponKickRandomness] = 0,
            [CombatFeelParameter.WeaponScalePunchX] = 0,
            [CombatFeelParameter.WeaponScalePunchY] = 0,
            [CombatFeelParameter.PlayerVisualRecoil] = 0,
            [CombatFeelParameter.PlayerVisualRecoilDuration] = .08f,
            [CombatFeelParameter.PlayerSquash] = 0,
            [CombatFeelParameter.PlayerStretch] = 0,
            [CombatFeelParameter.PlayerRotationKick] = 0,
            [CombatFeelParameter.PlayerReturnSpring] = 1,
            [CombatFeelParameter.PlayerRecoilVelocity] = 0,
            [CombatFeelParameter.MovementDamp] = 0,
            [CombatFeelParameter.MuzzleScale] = 1,
            [CombatFeelParameter.MuzzleDuration] = 1,
            [CombatFeelParameter.MuzzleBrightness] = 1,
            [CombatFeelParameter.MuzzleRandomRotation] = 0,
            [CombatFeelParameter.MuzzleStretch] = 1,
            [CombatFeelParameter.MuzzleSparks] = 1,
            [CombatFeelParameter.ProjectileScale] = 1,
            [CombatFeelParameter.ProjectileStretch] = 1,
            [CombatFeelParameter.ProjectileSquash] = 1,
            [CombatFeelParameter.ProjectileSpin] = 0,
            [CombatFeelParameter.ProjectileBrightness] = 1,
            [CombatFeelParameter.ProjectilePulse] = 0,
            [CombatFeelParameter.ProjectilePulseSpeed] = 8,
            [CombatFeelParameter.TrailWidth] = 1,
            [CombatFeelParameter.TrailLifetime] = 1,
            [CombatFeelParameter.TrailOpacity] = 1,
            [CombatFeelParameter.SpeedIllusion] = 0,
            [CombatFeelParameter.ForwardVisualOffset] = 0,
            [CombatFeelParameter.InitialStreakLength] = 0,
            [CombatFeelParameter.InitialStreakLifetime] = .06f,
            [CombatFeelParameter.ImpactScale] = 1,
            [CombatFeelParameter.ImpactLifetime] = 1,
            [CombatFeelParameter.ImpactBrightness] = 1,
            [CombatFeelParameter.ImpactRotationRandomness] = 0,
            [CombatFeelParameter.ImpactSparks] = 1,
            [CombatFeelParameter.PopupInitialScale] = 1,
            [CombatFeelParameter.PopupScalePunch] = 0,
            [CombatFeelParameter.PopupRiseSpeed] = 1.5f,
            [CombatFeelParameter.PopupLifetime] = 1,
            [CombatFeelParameter.PopupFadeDelay] = .55f,
            [CombatFeelParameter.PopupFadeDuration] = .45f,
            [CombatFeelParameter.PopupHorizontalDrift] = 0,
            [CombatFeelParameter.PopupDriftRandomness] = 0,
            [CombatFeelParameter.PopupRotation] = 0,
            [CombatFeelParameter.PopupRotationRandomness] = 0,
            [CombatFeelParameter.CritPopupScale] = 1.2f,
            [CombatFeelParameter.CritPopupRise] = 1,
            [CombatFeelParameter.CritPopupPunch] = 1,
            [CombatFeelParameter.CritPopupLifetime] = 1,
            [CombatFeelParameter.PopupDelay] = 0,
            [CombatFeelParameter.VisualHitPush] = 0,
            [CombatFeelParameter.HitPushDuration] = .03f,
            [CombatFeelParameter.HitReturnDuration] = .09f,
            [CombatFeelParameter.HitOvershoot] = 0,
            [CombatFeelParameter.HitSquashX] = 0,
            [CombatFeelParameter.HitStretchY] = 0,
            [CombatFeelParameter.HitSquashDuration] = .04f,
            [CombatFeelParameter.HitRestoreDuration] = .1f,
            [CombatFeelParameter.HitRotation] = 0,
            [CombatFeelParameter.HitRotationRandomness] = 0,
            [CombatFeelParameter.HitRotationReturn] = .12f,
            [CombatFeelParameter.WobbleStrength] = 0,
            [CombatFeelParameter.WobbleFrequency] = 12,
            [CombatFeelParameter.WobbleDamping] = 8,
            [CombatFeelParameter.DeathPush] = 0,
            [CombatFeelParameter.DeathRotation] = 0,
            [CombatFeelParameter.DeathSquash] = 0,
            [CombatFeelParameter.DeathStretch] = 0,
            [CombatFeelParameter.DeathScalePunch] = 0,
            [CombatFeelParameter.DeathHold] = 0,
            [CombatFeelParameter.DeathFade] = 0,
            [CombatFeelParameter.GhostLifetime] = .08f,
            [CombatFeelParameter.GhostScale] = 1,
            [CombatFeelParameter.GhostFade] = 1,
            [CombatFeelParameter.OverkillThreshold] = 1,
            [CombatFeelParameter.OverkillFeedback] = 1,
            [CombatFeelParameter.ShotShakeAmplitude] = 0,
            [CombatFeelParameter.ShotShakeDuration] = 0,
            [CombatFeelParameter.HitShakeAmplitude] = 0,
            [CombatFeelParameter.HitShakeDuration] = 0,
            [CombatFeelParameter.KillShakeAmplitude] = 0,
            [CombatFeelParameter.KillShakeDuration] = 0,
            [CombatFeelParameter.DirectionalKickDistance] = 0,
            [CombatFeelParameter.DirectionalKickDuration] = .03f,
            [CombatFeelParameter.DirectionalReturn] = .1f,
            [CombatFeelParameter.DirectionalOvershoot] = 0,
            [CombatFeelParameter.ShotZoomPunch] = 0,
            [CombatFeelParameter.HitZoomPunch] = 0,
            [CombatFeelParameter.KillZoomPunch] = 0,
            [CombatFeelParameter.ZoomAttack] = .025f,
            [CombatFeelParameter.ZoomReturn] = .12f,
            [CombatFeelParameter.TowardHit] = 0,
            [CombatFeelParameter.LookAheadDistance] = 0,
            [CombatFeelParameter.LookAheadResponse] = 8,
            [CombatFeelParameter.LookAheadReturn] = 6,
            [CombatFeelParameter.LookAheadDeadZone] = .08f,
            [CombatFeelParameter.LookAheadCurve] = 1,
            [CombatFeelParameter.HorizontalStrength] = 1,
            [CombatFeelParameter.VerticalStrength] = 1,
            [CombatFeelParameter.MaxScreenFraction] = .65f,
            [CombatFeelParameter.ShotFreeze] = 0,
            [CombatFeelParameter.ShotSlowdown] = 0,
            [CombatFeelParameter.ShotSlowdownScale] = 1,
            [CombatFeelParameter.ShotRecovery] = .08f,
            [CombatFeelParameter.HitFreeze] = 0,
            [CombatFeelParameter.HitSlowdown] = 0,
            [CombatFeelParameter.HitSlowdownScale] = 1,
            [CombatFeelParameter.HitRecovery] = .1f,
            [CombatFeelParameter.KillFreeze] = 0,
            [CombatFeelParameter.KillSlowdown] = 0,
            [CombatFeelParameter.KillSlowdownScale] = 1,
            [CombatFeelParameter.KillRecovery] = .14f,
            [CombatFeelParameter.EliteTimeEmphasis] = 1,
            [CombatFeelParameter.BossTimeEmphasis] = 1,
            [CombatFeelParameter.LocalEnemyFreeze] = 0,
            [CombatFeelParameter.FreezeBlend] = 0,
            [CombatFeelParameter.CrowdRadius] = 0,
            [CombatFeelParameter.CrowdStrength] = 0,
            [CombatFeelParameter.CrowdFalloff] = 1,
            [CombatFeelParameter.CrowdMaxTargets] = 0,
            [CombatFeelParameter.RapidKillWindow] = .5f,
            [CombatFeelParameter.RapidKillGain] = 0,
            [CombatFeelParameter.RapidKillMax] = 0,
            [CombatFeelParameter.RapidKillDecay] = 1,
            [CombatFeelParameter.PhysicalRecoil] = 0f,
            [CombatFeelParameter.GhostEnabled] = 0f,
            [CombatFeelParameter.MouseLookAhead] = 0f,
            [CombatFeelParameter.GlobalFreeze] = 0f,
    };

    public static float Get(CombatFeelParameter parameter) => values[parameter];
}
#endif
